apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:26.1.0
        args: [ "start-dev" ]
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "0.5"
            memory: "1Gi"
        envFrom:
        - configMapRef:
            name: keycloak-configmap
        - secretRef:
            name: keycloak-secrets
        env:
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-postgres-secrets
              key: POSTGRES_PASSWORD
        - name: KC_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: keycloak-postgres-secrets
              key: POSTGRES_USER
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 9000
