apiVersion: v1
kind: Secret
metadata:
    name: keycloak-postgres-secrets
type: Opaque
data:
    POSTGRES_DB: cG9zdGdyZXM=
    POSTGRES_USER: cG9zdGdyZXM=
    POSTGRES_PASSWORD: dmVyeV9zZWNyZXRfc2VjcmV0
